### ISSUE TITLE
Decide on a FOSS-License

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [tlm-solutions/strasi#11]

**Comment by TKFRvisionOfficial** [comment]
Kinda think about GPL-3 because of https://github.com/JaffaKetchup/flutter_map_tile_caching. But im not that convinced yet

**Comment by revol-xut** [comment]
Isn't MIT from an Organization standpoint the easiest ?

**Comment by TKFRvisionOfficial** [comment]
Yeah that or Apache-2 which I would be happy to go for. We just gotta think about the possibility that we want change to gpl3 in the future but this seems to be possible with both of them. I do not know how you want to license your own logo to prevent impersenation...
